routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    //==== Home
    Route::get('/', function () {
        return view('front-end.dashboard.index');
    });

    //==== Roles
    Route::group(['prefix' => 'roles'], function () {
        Route::get('/', 'RoleController@getIndex')->name('role.index');
        Route::get('api', 'Api\UserManagementController@getRoles')->name('role.api');
        Route::get('add', 'RoleController@getAdd')->name('role.add');
        Route::post('add', 'RoleController@postAdd')->name('role.post_add');
        Route::get('edit/{id}', 'RoleController@getEdit')->name('role.edit');
        Route::post('edit/{id}', 'RoleController@postEdit')->name('role.post_edit');
        Route::post('delete', 'RoleController@postDelete')->name('role.delete');
    });

    //==== Users
    Route::group(['prefix' => 'users'], function () {
        Route::get('/', 'UserController@getList')->name('user.index');
        Route::get('/api', 'Api\UserManagementController@getUsers')->name('user.api');
        Route::get('add', 'UserController@getAdd')->name('user.add');
        Route::post('add', 'UserController@postAdd')->name('user.post_add');
        Route::get('edit/{id}', 'UserController@getEdit')->name('user.edit');
        Route::post('edit/{id}', 'UserController@postEdit')->name('user.post_edit');
        Route::post('delete', 'UserController@postDelete')->name('user.delete');
    });
});

app/Http/Controllers/Api/UserManagementController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;

use App\Http\Controllers\Controller;
use App\Services\UserService;

class UserManagementController extends Controller
{
    protected $userService;

    public function __construct(UserService $userService)
    {
        $this->middleware('auth');
        $this->userService = $userService;
    }
    //api role
    public function getRoles()
    {
        return $this->userService->getRoles();
    }
    //api role
    public function getUsers()
    {
        return $this->userService->getUsers();
    }
    //api group
    public function getGroups()
    {
        return $this->userService->getGroups();
    }
}

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="user-id" content="{{ Auth::user()->id }}">
    <meta name="user-name" content="{{ Auth::user()->name }}">
    <meta name="api-base-url" content="{{ url('/') }}"/>
    <meta name="url_file" content="{{ url('/') }}"/>
    <meta name="locale" content="{{ App::getLocale() }}"/>
    {{-- <title>{{ setting('admin_title',config('app.name')) }}</title> --}}
    {{-- <link rel="shortcut icon" href="{{asset('/storage/avatar/'.setting('admin_favicon','favicon.png'))}}" sizes="32x32"> --}}
    <!-- Styles -->
    <link rel="stylesheet" href="{{asset('css/app.css')}}">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{{asset('lib/font-awesome/css/fontawesome.min.css')}}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{asset('css/material-font.css')}}">

    <link href="{{asset('css/main.css')}}" rel="stylesheet"/>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="{{asset('lib/bootstrap/css/bootstrap.min.css')}}">
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('lib/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
    <!-- Select2 -->
    <link rel="stylesheet" href="{{ asset('lib/select2/css/select2.min.css') }}">
    <!-- Jquery UI -->
    <link rel="stylesheet" href="{{ asset('lib/jquery/jquery-ui/jquery-ui.min.css') }}">
    <link href="{{asset('css/layout.css')}}" rel="stylesheet"/>
</head>
<body>
<div class="wrapper ">
    @include('layouts.sidebar')
    <main class="main-panel" id="app">
        @include('layouts.navbar')
        @include('blocks.message')
        @yield('content')
    </main>
    {{------------------------ Image modal box ---------------------- --}}
    <div id="imageModalBox" class="imageModal">
        <span class="imageModal-close">&times;</span>
        <img class="imageModal-content" id="imageModalBoxSrc">
    </div>
</div>
<!-- jQuery -->
<script src="{{ asset('lib/jquery/jquery.min.js') }}"></script>
<!-- Bootstrap  -->
<script src="{{ asset('lib/material/js/core/popper.min.js') }}"></script>
<script src="{{ asset('lib/material/js/core/bootstrap-material-design.min.js') }}"></script>

@stack('page-scripts')
<script src="{{ asset('lib/bootstrap/js/bootstrap.min.js') }}"></script>
<!-- DataTables -->
<script src="{{ asset('lib/datatables/jquery.dataTables.js') }}"></script>
<script src="{{ asset('lib/datatables-bs4/js/dataTables.bootstrap4.js') }}"></script>
<script src="{{asset('lib/material/js/plugins/perfect-scrollbar.jquery.min.js')}}"></script>
<!-- Select 2 -->
<script src="{{ asset('lib/select2/js/select2.full.min.js') }}"></script>

<script src="{{asset('js/main.js')}}"></script>
<script src="{{asset('js/autosize.js')}}"></script>
<script src="{{ asset('js/chat.js') }}"></script>
<script src="{{ asset('js/dashboard.js') }}"></script>
<script type="text/javascript">
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });
    $(document).ready(function () {
        let url = window.location;
        let element = $('.nav .nav-item a').filter(function () {
            return this.href == url || window.location.pathname == 0;
        });
        $(element).parentsUntil('ul.sidebar-menu', 'li').addClass('active');
        $('#notifications').click(function () {
            $('#list-notifications').toggle()
        });
        $('#languageDropdown').click(function () {
            $('#list-language').toggle()
        })
    });
</script>
@stack('script')

</body>
</html>

resources/views/layouts/navbar.blade.php
{{--Start Navbar--}}
<nav class="navbar navbar-expand-lg  ">

    <div class="container-fluid ">
        <div class="navbar-wrapper">
            <a class="navbar-brand" href="javascript:;"></a>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="javascript:;">
                        <i class="material-icons">dashboard</i>
                        <p class="d-lg-none d-md-block">
                            Stats
                        </p>
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="http://example.com" id="notifications" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        <i class="material-icons">notifications</i>
                        <span class="notification">{{$total}}</span>
                        <p class="d-lg-none d-md-block">
                            Some Actions
                        </p>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink"
                         id="list-notifications">
                            @if($total >0 )
                                @foreach ($list as $notification)
                                    <a class="dropdown-item" href="{{url('/detail-report/'.$notification->data['report_id'])}}">
                                        <img src="{{asset('storage/avatar/'.$notification->avatar)}}" class="avatar-notification">
                                        @if(empty($notification->data['to_id']))
                                            <span class="font-weight-bold">{{ $notification->name }}</span> {{__('layout.reminded')}}
                                        @else
                                            <span class="font-weight-bold">{{ $notification->name }}  {{__('layout.commented')}}</span>
                                        @endif
                                        <br>
                                        <span class="time-notification">
                                                {{Carbon\Carbon::parse( $notification->data['created_at'])->locale(app()->getLocale())->diffForHumans() }}
                                            </span>
                                    </a>
                                @endforeach
                            @else
                                <a class="dropdown-item" href="">{{__('layout.notification')}}  </a>
                            @endif
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link flex-row" href="javascript:;" id="languageDropdown" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        <i class="material-icons">language</i>
                        {{ App::getLocale() == 'en'  ? 'EN':' JP'  }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile"
                         id="list-language">
                        <a class="dropdown-item " href="{{url('lang/en')}}">English
                            <img src="{{asset('img/en.png')}}"></a>
                        <a class="dropdown-item" href="{{url('lang/ja')}}">Japan
                            <img src="{{asset('img/jp.png')}}"></a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

{{--<--End Nav-->--}}

resources/views/layouts/sidebar.blade.php
<div class="sidebar" data-color="purple" data-background-color="white" data-image="{{asset('lib/material/img/sidebar-1.jpg')}}">
    <div class="logo">
        <a href="{{url('/')}}" class="simple-text logo-normal">
            <img src="{{asset('/storage/avatar/logo.png')}}">
        </a></div>
    <div class="sidebar-wrapper ps-container ps-theme-default" data-ps-id="842f1926-37f2-1d8e-6e1b-7992efd763ba">
        <ul class="nav">
            <li class="nav-item  ">
                <a class="nav-link" href="{{url('dashboard')}}">
                    <i class="material-icons">dashboard</i>
                    <p>{{__("layout.dashboard")}}</p>
                </a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{url('profile')}}">
                    <i class="fa fa-user-circle"></i>
                    <p>{{__("layout.user_profile")}}</p>
                </a>
            </li>
            {{-- <li class="nav-item ">
                <a class="nav-link" href="{{url('report')}}">
                    <i class="material-icons">content_paste</i>
                    <p>{{__("layout.calendar_report")}}</p>
                </a>
            </li> --}}
            
            {{-- <li class="nav-item ">
                <a class="nav-link" href="{{url('user-report')}}">
                    <i class="fa fa-list"></i>
                    <p>{{__("layout.list_user_report")}}</p>
                </a>
            </li> --}}

            <li class="nav-item ">
                <a class="nav-link" href="{{ route('user.index') }}">
                    <i class="material-icons">person</i>
                    <p>{{__("layout.users")}}</p>
                </a>
            </li>

            <li class="nav-item ">
                <a class="nav-link" href="{{ route('role.index') }}">
                    <i class="material-icons">device_hub</i>
                    <p>{{__("layout.roles")}}</p>
                </a>
            </li>

            {{-- <li class="nav-item ">
                <a class="nav-link" href="{{ route('front-end.group.index') }}">
                    <i class="material-icons">group</i>
                    <p>{{__("layout.groups")}}</p>
                </a>
            </li> --}}

            {{-- <li class="nav-item">
                <a class="nav-link" href="{{ route('front-end.activity.index') }}">
                    <i class="material-icons">flip_to_front</i>
                    <p>{{__("layout.activity_logs")}}</p>
                </a>
            </li> --}}

            {{-- <li class="nav-item ">
                <a class="nav-link" href="{{url('/settings/email')}}">
                    <i class="material-icons">settings</i>
                    <p>{{__("layout.setting")}}</p>
                </a>
            </li> --}}

            <li class="nav-item ">
                <a class="nav-link" href="{{ route('logout') }}"
                    onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();">

                    <i class="material-icons">logout</i>
                    <p> {{ __('layout.logout') }}</p>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST"
                          style="display: none;">
                        @csrf
                    </form>
                </a>
            </li>
        </ul>
        <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 0px;">
            <div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div>
        </div>
        <div class="ps-scrollbar-y-rail" style="top: 0px; right: 0px;">
            <div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div>
        </div>
    </div>
</div>